namespace Packt.Shared;
// this file simulates an autogenerated class
public partial class Person
{
    // a readonly property defined using C# 1 - 5 syntax
    public string Origin
    {
        get
        {
            return string.Format("{0} was born on {1}",
            arg0: Name, arg1: HomePlanet);
        }
    }
    // two readonly properties defined using C# 6+ lambda expression bodysyntax
    public string Greeting => $"{Name} says 'Hello!'";
    public int Age => DateTime.Today.Year - DateOfBirth.Year;
}